Upload and download from/to file, fileobj or string
exasol/bucketfs-utils-python pull request #21
Opened 2021-02-17 09:20 UTC by tkilias

Fixes #6
Fixes #7

2021-03-03 16:54 UTC, tkilias commented
@AnastasiiaSergienko  could check the pull request, while I am on vacation. It is almost done, only the documentation and the runtime type checks in upload.py and download.py are missing.

2021-03-08 12:07 UTC, AnastasiiaSergienko commented on tests/test_bucketfs_config.py
> +        connection_config = BucketFSConnectionConfig(host="localhost", port=6666, user="w", pwd="write",
This can go outside of raises, right?

2021-03-08 12:07 UTC, AnastasiiaSergienko commented on tests/test_bucketfs_config.py
> +    bucketfs_config = BucketFSConfig(bucketfs_name=bucketfs_name, connection_config=connection_config)
This can also be a method probably

2021-03-09 14:44 UTC, tkilias commented on exasol_bucketfs_utils_python/bucketfs_utils.py
> +ARCHIVE_EXTENSIONS = [".tar.gz", ".tar.bz2", ".zip", ".tar"]
good catch, had somehow the wrong extensions in mind

2021-03-09 14:45 UTC, tkilias commented on exasol_bucketfs_utils_python/bucketfs_utils.py
> +            print(path_in_bucket)
missed that, somehow, thx

2021-03-09 14:45 UTC, tkilias commented on exasol_bucketfs_utils_python/bucketfs_utils.py
> +    the given Path in a bucket in there file system
ups, typo, meant 'their'

2021-03-09 14:48 UTC, tkilias commented on exasol_bucketfs_utils_python/bucketfs_utils.py
> +def create_auth_object(bucket_config: BucketConfig) -> HTTPBasicAuth:
it wasn't thought as part of the public interface, but it shouldn't hurt to add it

2021-03-09 14:49 UTC, tkilias commented on exasol_bucketfs_utils_python/download.py
> +def download_object_from_bucketfs_via_joblib(bucket_config: BucketConfig, bucket_file_path: str):
yep, I wasn't done with them

2021-03-09 15:03 UTC, tkilias commented on exasol_bucketfs_utils_python/bucketfs_utils.py
> +ARCHIVE_EXTENSIONS = [".tar.gz", ".tar.bz2", ".zip", ".tar"]
done with last commit

2021-03-09 15:04 UTC, tkilias commented on tests/test_bucketfs_config.py
> +        connection_config = BucketFSConnectionConfig(host="localhost", port=6666, user="w", pwd="write",
ah, yes you are right

2021-03-09 15:13 UTC, tkilias commented on tests/test_bucketfs_config.py
> +    bucketfs_config = BucketFSConfig(bucketfs_name=bucketfs_name, connection_config=connection_config)
done

2021-03-09 15:13 UTC, tkilias commented on tests/test_bucketfs_config.py
> +        connection_config = BucketFSConnectionConfig(host="localhost", port=6666, user="w", pwd="write",
done

2021-03-09 15:14 UTC, tkilias commented on tests/test_bucket_config.py
> +    bucketfs_config = BucketFSConfig(bucketfs_name="bfsdefault", connection_config=connection_config)
done

2021-03-09 15:16 UTC, tkilias commented on exasol_bucketfs_utils_python/bucketfs_utils.py
> +def create_auth_object(bucket_config: BucketConfig) -> HTTPBasicAuth:
done

2021-03-09 15:17 UTC, tkilias commented on exasol_bucketfs_utils_python/bucketfs_utils.py
> +            print(path_in_bucket)
done

2021-03-09 15:21 UTC, tkilias commented on exasol_bucketfs_utils_python/bucketfs_utils.py
> +    the given Path in a bucket in there file system
done

2021-03-19 10:46 UTC, AnastasiiaSergienko requested changes
Found some typos

2021-03-19 10:46 UTC, AnastasiiaSergienko commented on exasol_bucketfs_utils_python/bucketfs_utils.py
> +    the given Path in a bucket in their file system
```suggestion
    the given path in a bucket in their file system
```

2021-03-19 10:46 UTC, AnastasiiaSergienko commented on exasol_bucketfs_utils_python/bucketfs_utils.py
> +    the given Path in a bucket in their file system
Or it can be uppercase but in other places too. It looks prettier when we unify them

2021-03-19 10:46 UTC, AnastasiiaSergienko commented on exasol_bucketfs_utils_python/bucketfs_utils.py
> +    with or without basic authentication  (http[s]://user:password@host:port)
```suggestion
    with or without basic authentication  (a template: http[s]://user:password@host:port)
```

2021-03-19 10:46 UTC, AnastasiiaSergienko commented on exasol_bucketfs_utils_python/bucketfs_utils.py
> +    with or without basic authentication  (http[s]://user:password@host:port)
```suggestion
    with or without basic authentication  (a template: http[s]://user:password@host:port)
```

2021-03-19 10:46 UTC, AnastasiiaSergienko commented on exasol_bucketfs_utils_python/upload.py
> +    This function uploads a file to the specified path in bucket of the BucketFS.
```suggestion
    This function uploads a file to the specified path in a bucket of the BucketFS.
```

2021-03-19 10:46 UTC, AnastasiiaSergienko commented on exasol_bucketfs_utils_python/upload.py
> +    This function uploads a string to the specified path in bucket of the BucketFS.
```suggestion
    This function uploads a string to the specified path in a bucket of the BucketFS.
```

2021-03-19 10:46 UTC, AnastasiiaSergienko commented on exasol_bucketfs_utils_python/upload.py
> +    and uploads it to the specified path in bucket of the BucketFS.
```suggestion
    and uploads it to the specified path in a bucket of the BucketFS.
```

2021-03-19 10:46 UTC, AnastasiiaSergienko commented on exasol_bucketfs_utils_python/upload.py
> +    :param object: Object which gets serialized and uploaed via joblib.dump
```suggestion
    :param object: Object which gets serialized and uploaded via joblib.dump
```

2021-03-19 10:46 UTC, AnastasiiaSergienko commented on exasol_bucketfs_utils_python/upload.py
> +    :param kwargs: Keyword arguments which get forwared to joblib.dump
```suggestion
    :param kwargs: Keyword arguments which get forwarded to joblib.dump
```

2021-03-19 12:10 UTC, merged