Use sphinx for documentation
exasol/bucketfs-utils-python pull request #31
Opened 2021-06-10 17:38 UTC by tkilias

- This pull request integrates sphinx into our documentation and repository layout. 
- It enables us to deploy the documentation for all released versions on github pages
- The existing documentation was transformed to restructuredText and gets now build with sphinx
- Sphinx also can build an API Documentation for us.

2021-06-10 18:58 UTC, tomuben commented on .github/workflows/check_github_pages_docs_for_current.yaml
> +      - main
Why main branch needs to be ignored?

2021-06-10 19:01 UTC, tomuben commented on .github/workflows/deploy_github_pages_docs_for_main.yaml
> +    branches-ignore:
Do you need branches-ignore if there is also a explict filter for main?

2021-06-10 19:47 UTC, tomuben commented on doc/conf.py
> +    '.txt': 'markdown',
Not text?

2021-06-10 19:56 UTC, tomuben commented on doc/deploy-to-github-pages.sh
> +detect_source_branch() {
Please check name. Actually this method only verifies SOURCE_BRANCH

2021-06-10 20:10 UTC, tomuben commented on doc/deploy-to-github-pages.sh
> +    git reset --hard "$SOURCE_BRANCH"
Why don't create just a branch based on SOURCE_BRANCH here with:
```
git checkout -b "$TARGET_BRANCH" $SOURCE_BRANCH
```
?

2021-06-10 20:19 UTC, tomuben reviewed
Please check my comments.

2021-06-11 07:06 UTC, tkilias commented on .github/workflows/deploy_github_pages_docs_for_main.yaml
> +    branches-ignore:
This an error, I also saw yesterday, but had no time to fix, yet

2021-06-11 07:07 UTC, tkilias commented on doc/conf.py
> +    '.txt': 'markdown',
I copied that from the documentation of myst-parser

2021-06-11 07:11 UTC, tkilias commented on doc/deploy-to-github-pages.sh
> +    git reset --hard "$SOURCE_BRANCH"
I need a worktree, because I need source branch and target branch at the same time. However, the git reset SOURCE_BRANCH looks wrong

2021-06-11 08:22 UTC, tkilias commented on .github/workflows/check_github_pages_docs_for_current.yaml
> +    - name: Test deploy documentation to github-pages-main branch
No, this one only runs the deployment to test if it works and to check if the documentation builds without warnings or errors. We don't have push enabled for this run.

2021-06-11 08:52 UTC, tkilias commented on doc/deploy-to-github-pages.sh
> +detect_source_branch() {
It can also set it to CURRENT_BRANCH, if the SOURCE_BRANCH is not given. However, for clarity I renamed it to detect_or_verify_source_branch

2021-06-11 15:06 UTC, tkilias commented
Add to the developer guide, how to build the documentation.
`poetry run poe build-and-open-html-doc`

2021-06-11 18:59 UTC, tomuben commented
> Add to the developer guide, how to build the documentation.
> `poetry run poe build-and-open-html-doc`

Managed to build the documentation, works like a charm. Just one observation: The footnote shows your name in the copyright...I'am not sure if this is hard coded somewhere, and if it's not better to show "Exasol"....

2021-06-11 19:05 UTC, tomuben commented on .github/workflows/check_github_pages_docs_for_feature_branch.yaml
> +        git push origin --delete "$TARGET_BRANCH"
Just to understand correctly, your goal is to test **only** deployment, immediately afterwards you delete the branch on github-pages, right?
As alternative, we could keep the documentation for feature pages on github pages, and delete as soon as the feature branch gets deleted....

2021-06-11 19:20 UTC, tomuben requested changes

2021-06-11 19:20 UTC, tomuben commented on doc/changes/changes_0.1.0.md
keep one blank line

2021-06-11 19:20 UTC, tomuben commented on doc/conf.py
> +copyright = '2021, Torsten Kilias'
Please check if copyright is correct. 
Maybe better: 
copyright = '2021, The BucketFS Utils Python team' or
copyright = '2021, Exasol'

2021-06-11 19:20 UTC, tomuben commented on doc/conf.py
> +author = 'Torsten Kilias'
Same as above

2021-06-11 19:20 UTC, tomuben commented on doc/deploy-to-github-pages.sh
> +    git reset --hard "$SOURCE_BRANCH"
Well, the git reset is still there....

2021-06-14 09:14 UTC, tkilias commented on doc/conf.py
> +copyright = '2021, Torsten Kilias'
Good point, I think, that was generated when I created the project.

2021-06-14 09:18 UTC, tkilias commented on .github/workflows/check_github_pages_docs_for_feature_branch.yaml
> +        git push origin --delete "$TARGET_BRANCH"
I am not generating here the actual github-pages branch, it is a different one. If I added the feature-branch documentation to the actual github-pages branch, I would need to commit it there, and it would stay forever in the history of this branch. Doesn't sound like a good idea for me. Usually, for review you can review the sources, and if things are really unclear you still can build locally.

2021-06-22 11:34 UTC, tomuben commented on doc/deploy-to-github-pages.sh
> +    fi
Do we define the default branch for github-branches, or is this defined by Github?
Does it make sense to support only main and root, not master for example?

2021-06-22 13:22 UTC, tkilias commented on doc/deploy-to-github-pages.sh
> +    fi
The default branch from github for pages is gh-pages, but you can change that. And, not using the default branch actually has benefits, because branch gh-pages enforces some things. We use root and main, because root is the new git root and main is the new master. Master is a banned word and we are going to migrate more and more repos to main

2021-06-22 19:07 UTC, tomuben commented on doc/changes/changes_0.1.0.md
# BucketFs Utily Python 0.1.0, released XYZ

2021-06-22 19:11 UTC, tomuben commented on doc/deploy-to-github-pages.sh
> +    GH_PAGES_ROOT_BRANCH=origin/github-pages/root
I still don't understand why we need this new root branch at all, sorry.

2021-06-22 19:12 UTC, tomuben commented on doc/deploy-to-github-pages.sh
> +    # We use github-pages/root and github-pagesmain, because github-pages/root is the new git root for the github pages
github-pages/main

2021-06-23 09:46 UTC, tkilias commented on doc/deploy-to-github-pages.sh
> +    # We use github-pages/root and github-pagesmain, because github-pages/root is the new git root for the github pages
```suggestion
    # We use github-pages/root and github-pages/main, because github-pages/root is the new git root for the github pages
```

2021-06-23 09:47 UTC, tkilias commented on doc/changes/changes_0.1.0.md
```suggestion
# BucketFs Utily Python 0.1.0, released XYZ
```

2021-06-24 10:27 UTC, tomuben commented on doc/changes/changes_0.1.0.md
> +# BucketFs Utily Python 0.1.0, released XYZ
Got somehow duplicated

'''
# BucketFS Utils Python 0.1.0, released 2020-11-??
'''

2021-06-24 10:32 UTC, tomuben commented on doc/developer_guide/building_documentation.rst
> +Sphinx supports API generation for Python and with plugins also for other languages.
Is it really API generation? Not "documentation generation of API"?

2021-06-24 10:32 UTC, tomuben commented on doc/developer_guide/building_documentation.rst
> +Furthermore, it supports reStructuredText with proper cros-document references.
```suggestion
Furthermore, it supports reStructuredText with proper cross-document references.
```

2021-06-24 10:34 UTC, tomuben commented on doc/developer_guide/building_documentation.rst
> +which allow you to build and view the documentation during coding::
```suggestion
We defined several commands in the project.toml in poethepoet
which allow you to build and view the documentation during coding:
```

2021-06-24 10:35 UTC, tomuben commented on doc/developer_guide/building_documentation.rst
> +All three commands build use the builded documentation located in/doc/_build/
```suggestion
All three commands build use the builded documentation located in /doc/_build/
```

2021-06-24 10:36 UTC, tomuben commented on doc/developer_guide/building_documentation.rst
> +which is excluded in gitignore. If you want to build the documentation to other formats than HTML,
```suggestion
which is excluded in gitignore. If you want to build the documentation for other formats than HTML,
```

2021-06-24 10:37 UTC, tomuben commented on doc/developer_guide/building_documentation.rst
> +because we in also contains the preperations for publishing. At the moment, we publish
```suggestion
Building the Documentation in the CI is a bit different to the steps you can use during coding,
because those steps also contain the preparations for publishing. At the moment, we publish
```

2021-06-24 10:39 UTC, tkilias commented on doc/developer_guide/building_documentation.rst
> +which allow you to build and view the documentation during coding::
reStructuredText Syntax for code blocks

2021-06-24 10:40 UTC, tomuben commented on doc/developer_guide/building_documentation.rst
> +we add a directory to the root directory of the github-pages/main branch.
```suggestion
For each branch or tag for which we build the documentation in the CI
we add a directory to the root directory of the github-pages/main branch.
```

2021-06-24 10:42 UTC, tkilias commented on doc/developer_guide/building_documentation.rst
> +Sphinx supports API generation for Python and with plugins also for other languages.
```suggestion
Sphinx supports API documentation generation for Python and with plugins also for other languages.
```

2021-06-24 10:43 UTC, tomuben commented on doc/developer_guide/building_documentation.rst
> +We again a few shortcuts defined in our project.toml for poethepoet::
```suggestion
We also provide a few shortcuts defined in our project.toml for poethepoet::
```

2021-06-24 10:44 UTC, tkilias commented on doc/developer_guide/building_documentation.rst
> +because we in also contains the preperations for publishing. At the moment, we publish
```suggestion
Building the documentation in the CI is a bit different to the steps you can use during coding,
because it also contain the preparations for publishing. At the moment, we publish
```

2021-06-24 11:31 UTC, tomuben approved these changes

2021-06-24 12:41 UTC, merged