#3: Added github workflow for releasing on PyPI.
exasol/bucketfs-utils-python pull request #4
Opened 2020-11-18 15:04 UTC by AnastasiiaSergienko

2020-11-18 15:53 UTC, tkilias requested changes

2020-11-18 15:53 UTC, tkilias commented on .github/workflows/release_workflow.yaml
> +
I think, here is the second asset missing. Poetry creates also a sdist (source distribution) file besides the tar.gz. We need to upload this to GitHub as well.

2020-11-18 15:53 UTC, tkilias commented on .github/workflows/release_workflow.yaml
> +      - name: Publish distribution to PyPI
I am thinking about if we want to add for the moment a condition to the PyPI upload, which checks if the secrets exists and only executes the PyPI upload if it exists. This would allow us testing.

2022-06-21 13:58 UTC, Nicoretti commented
This PR is outdated and therefore will be abandoned.

2022-06-21 13:58 UTC, closed without merging