#76: Corrected and updated generate udf path method
exasol/bucketfs-utils-python pull request #78
Opened 2022-08-04 08:40 UTC by umitbuyuksahin

Fixes #76

2022-08-04 10:09 UTC, tkilias requested changes

2022-08-04 10:09 UTC, tkilias commented on exasol_bucketfs_utils_python/bucketfs_location.py
> +        if bucket_file_path is not None:
what do you do, if it is None, does PurePosixPath ignore it?

2022-08-04 10:09 UTC, tkilias commented on exasol_bucketfs_utils_python/bucketfs_location.py
> +        if bucket_file_path is not None:
you need to add a test parameter for None

2022-08-04 10:09 UTC, tkilias commented on tests/integration_tests/without_db/test_bucketfs_location.py
> +        BucketFSLocation(bucket_config, base_path=PurePosixPath(""))
can be the base_path None?

2022-08-04 10:09 UTC, tkilias commented on tests/integration_tests/without_db/test_bucketfs_location.py
> +        BucketFSLocation(bucket_config, base_path=PurePosixPath(""))
I suggest to split with and without base_path into two tests, makes it more obvious

2022-08-04 10:19 UTC, umitbuyuksahin commented on exasol_bucketfs_utils_python/bucketfs_location.py
> +        if bucket_file_path is not None:
PurePosixPath raises error for null input

2022-08-04 10:25 UTC, umitbuyuksahin commented on tests/integration_tests/without_db/test_bucketfs_location.py
> +        BucketFSLocation(bucket_config, base_path=PurePosixPath(""))
base_path shouldn't be None.
it might be better to make it empty string in case of None input, should we ?

2022-08-04 10:32 UTC, tkilias commented on tests/integration_tests/without_db/test_bucketfs_location.py
> +        BucketFSLocation(bucket_config, base_path=PurePosixPath(""))
Actually, it should be an optional parameter and as this None, at least that what I intended.

2022-08-04 10:32 UTC, tkilias commented on exasol_bucketfs_utils_python/bucketfs_location.py
> +        if bucket_file_path is not None:
than you need to handle None

2022-08-05 06:46 UTC, tkilias requested changes

2022-08-05 06:46 UTC, tkilias commented on tests/integration_tests/without_db/test_bucketfs_location.py
> +def test_generate_bucket_udf_path_with_base_path(path_in_bucket):
```suggestion
def test_generate_bucket_udf_path_without_base_path(path_in_bucket):
```

2022-08-05 06:46 UTC, tkilias commented on exasol_bucketfs_utils_python/bucketfs_location.py
> +    def __init__(self, bucket_config: BucketConfig,
Did you change the base_path handling also in the MockBucketFSLocation?

2022-08-05 06:46 UTC, tkilias commented on doc/changes/changes_0.4.0.md
> + - #72: Added tests for the fixed generating bucket udf path method
Mention the change of the handling of None for the base_path

2022-08-05 07:38 UTC, tkilias requested changes

2022-08-05 07:38 UTC, tkilias commented on exasol_bucketfs_utils_python/localfs_mock_bucketfs_location.py
>      def get_complete_file_path_in_bucket(self, bucket_file_path) -> str:
Type for bucket_file_path is missing

2022-08-05 07:38 UTC, tkilias commented on exasol_bucketfs_utils_python/bucketfs_location.py
>              bucket_file_path: str) -> str:
wrong type, we should use PurePosixPath

2022-08-05 07:38 UTC, tkilias commented on exasol_bucketfs_utils_python/localfs_mock_bucketfs_location.py
>      def get_complete_file_path_in_bucket(self, bucket_file_path) -> str:
we also should use PurePosixPath

2022-08-05 07:45 UTC, umitbuyuksahin commented on exasol_bucketfs_utils_python/bucketfs_location.py
>              bucket_file_path: str) -> str:
it is used as string in almost entire the project

2022-08-05 08:14 UTC, tkilias approved these changes

2022-08-05 09:16 UTC, merged