#81: Updated poetry and udf mock
exasol/bucketfs-utils-python pull request #82
Opened 2022-08-31 10:59 UTC by MarleneKress79789

fixes #81

2022-08-31 11:40 UTC, tkilias requested changes

2022-08-31 11:40 UTC, tkilias commented on scripts/build/poetry_utils.sh
> +  sed -i 's/allowed_executables = \["python", "python3"\]/allowed_executables = ["python3", "python"]/'  install-python-poetry.py
this is not necessary anymore, they fixed this with the new installer

2022-09-01 11:09 UTC, MarleneKress79789 commented on scripts/build/poetry_utils.sh
> +  sed -i 's/allowed_executables = \["python", "python3"\]/allowed_executables = ["python3", "python"]/'  install-python-poetry.py
Which part are you talking about? just the line 13 or the whole function checking weather the install worked?

2022-09-01 11:16 UTC, tkilias commented on scripts/build/poetry_utils.sh
> +  sed -i 's/allowed_executables = \["python", "python3"\]/allowed_executables = ["python3", "python"]/'  install-python-poetry.py
the sed part

2022-09-01 11:29 UTC, MarleneKress79789 commented on scripts/build/poetry_utils.sh
> +  sed -i 's/allowed_executables = \["python", "python3"\]/allowed_executables = ["python3", "python"]/'  install-python-poetry.py
removed

2022-09-01 11:36 UTC, tkilias reviewed
Could you also mark setup.py and poetry.lock as generated.

2022-09-01 11:44 UTC, tkilias approved these changes

2022-09-01 11:54 UTC, merged